[project]
name = "youtube-subtitles-downlaoder"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "dotenv>=0.9.9",
    "flask>=3.1.2",
    "requests>=2.32.5",
    "telebot>=0.0.5",
    "termcolor>=3.2.0",
]
